git clone git@github.com:DC-Melo/YouCompleteMe-clang.git
git clone git@github.com:DC-Melo/vim-edit.git
git clone git@github.com:DC-Melo/gv.vim.git
git clone git@github.com:DC-Melo/vim-textobj-syntax.git
git clone git@github.com:DC-Melo/vimplus-startify.git
git clone git@github.com:DC-Melo/vim-textobj-function.git
git clone git@github.com:DC-Melo/nerdtree-git-plugin.git
git clone git@github.com:DC-Melo/auto-pairs.git
git clone git@github.com:DC-Melo/echodoc.vim.git
git clone git@github.com:DC-Melo/vim-multiple-cursors.git
git clone git@github.com:DC-Melo/vim-airline-themes.git
git clone git@github.com:DC-Melo/vim-surround.git
git clone git@github.com:DC-Melo/vim-airline.git
git clone git@github.com:DC-Melo/vim-endwise.git
git clone git@github.com:DC-Melo/tagbar.git
git clone git@github.com:DC-Melo/prepare-code.git
git clone git@github.com:DC-Melo/tabular.git
git clone git@github.com:DC-Melo/vim-cpp-enhanced-highlight.git
git clone git@github.com:DC-Melo/vim-repeat.git
git clone git@github.com:DC-Melo/clever-f.vim.git
git clone git@github.com:DC-Melo/vim-textobj-user.git
git clone git@github.com:DC-Melo/ultisnips.git
git clone git@github.com:DC-Melo/gsession.vim.git
git clone git@github.com:DC-Melo/VisIncr.git
git clone git@github.com:DC-Melo/DrawIt.git
git clone git@github.com:DC-Melo/vim-buffer.git
git clone git@github.com:DC-Melo/vim-fugitive.git
git clone git@github.com:DC-Melo/LeaderF.git
git clone git@github.com:DC-Melo/incsearch.vim.git
git clone git@github.com:DC-Melo/change-colorscheme.git
git clone git@github.com:DC-Melo/cpp-mode.git
git clone git@github.com:DC-Melo/vim-nerdtree-syntax-highlight.git
git clone git@github.com:DC-Melo/vim-devicons.git
git clone git@github.com:DC-Melo/vim-slash.git
git clone git@github.com:DC-Melo/indentpython.vim.git
git clone git@github.com:DC-Melo/vim-smooth-scroll.git
git clone git@github.com:DC-Melo/vim-textobj-indent.git
git clone git@github.com:DC-Melo/vim-textobj-parameter.git
git clone git@github.com:DC-Melo/vim-commentary.git
git clone git@github.com:DC-Melo/nerdtree.git
git clone git@github.com:DC-Melo/ack.vim.git
git clone git@github.com:DC-Melo/vim-easymotion.git
git clone git@github.com:DC-Melo/vim-snippets.git
