find BFS                   \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_BFS.snippets
find Binary_Search         \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Binary_Search.snippets
find Bit_Manipulation      \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Bit_Manipulation.snippets
find Deque                 \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Deque.snippets
find Design                \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Design.snippets
find DFS                   \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_DFS.snippets
find Divide_Conquer        \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Divide_Conquer.snippets
find Dynamic_Programming   \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Dynamic_Programming.snippets
find Graph                 \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Graph.snippets
find Greedy                \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Greedy.snippets
find Hash                  \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Hash.snippets
find Heap                  \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Heap.snippets
find LCCUP                 \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_LCCUP.snippets
find Linked_List           \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Linked_List.snippets
find Math                  \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Math.snippets
find Others                \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Others.snippets
find Priority_Queue        \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Priority_Queue.snippets
find Readme.md             \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Readme.md.snippets
find Recursion             \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Recursion.snippets
find Segment_Tree          \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Segment_Tree.snippets
find Simulation            \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Simulation.snippets
find Stack                 \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Stack.snippets
find String                \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_String.snippets
find Template              \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Template.snippets
find tests                 \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_tests.snippets
find Tree                  \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Tree.snippets
find Trie                  \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Trie.snippets
find Two_Pointers          \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Two_Pointers.snippets
find Union_Find            \(  -iname "*.cpp" -o -iname "*.md" \)  -print0 | sort -z | xargs -r0 more >              cpp_Union_Find.snippets
